version: '3'
services:
  backend:
      build: .
      ports:
        - "3000:3000"
      depends_on:
        - mongo
      environment:
        - MONGO_URI=mongodb://mongo:27017
        - PORT=3000
        - MONGO_DB=idolhandshake
        - JWT_SECRET=fsdfsdfsdfsdfsd
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
    
  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
